/// <reference types="nativewind/types" />

// NOTE: This file should not be edited and should be committed with your source code. It is generated by NativeWind.
// If you need to customize your TypeScript configuration, please refer to the NativeWind documentation.
